name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build and deploy:
    name: Build and deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
        
      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build
        run: go build -v .
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.0
        with:
          node-version: '10.x'
      
      - run: cd frontend && npm install && npm run build
        
      - name: SCP Files
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "audio-cut,frontend/dist"
          target: "/root/audio-cut"
